In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import sys
import os
sys.path.append(os.path.abspath('../../'))

In [3]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

In [4]:
bad_sessions = [ 21,  20, 162,  14, 163, 160, 167]

In [5]:
base_cols = [
            'target_queue_len', 'others_len_queue', 'iat_fqdn', 'num_running_funcs_filled',
            'gpu_warm_results_sec', 'gpu_cold_results_sec', 'is_cold_start'
        ]

In [6]:
error_data = pd.read_csv('../data/processed/results/error_data/rf_model_results.csv')

In [7]:
error_data.columns

Index(['session', 'fqdn', 'tid', 'dispatch_policy', 'e2etime', 'rf_prediction',
       'absolute_error', 'squared_error', 'percentage_relative_error',
       'is_test'],
      dtype='object')

In [8]:
error_data[error_data.is_test==True]['session'].unique()

array([0])

In [9]:
error_data[error_data.is_test==True][['fqdn', 'percentage_relative_error']].groupby('fqdn').mean().sort_values(by='percentage_relative_error')

                         percentage_relative_error
fqdn
pyhpc-eos-3-0.0.1                      -489.187404
torch_rnn-4-0.0.1                      -476.383572
pyhpc-eos-2-0.0.1                      -403.049604
torch_rnn-3-0.0.1                      -353.782845
pyhpc-eos-1-0.0.1                      -330.725695
pyhpc-eos-4-0.0.1                      -325.019960
torch_rnn-0-0.0.1                      -312.267654
pyhpc-eos-0-0.0.1                      -302.822050
torch_rnn-2-0.0.1                      -299.062247
pyhpc-isoneural-3-0.0.1                -214.068582
pyhpc-isoneural-1-0.0.1                -191.663541
torch_rnn-1-0.0.1                      -170.097983
pyhpc-isoneural-0-0.0.1                -159.908520
pyhpc-isoneural-2-0.0.1                 -86.784524
squeezenet-2-0.0.1                      -30.010025
onnx-roberta-2-0.0.1                    -27.758969
onnx-roberta-0-0.0.1                    -22.064506
onnx-roberta-3-0.0.1                    -21.926748
squeezenet-4-0.0.1                      -19.283166
onnx-roberta-1-0.0.1                    -18.701199
squeezenet-1-0.0.1                      -16.937783
onnx-roberta-4-0.0.1                    -15.418565
cupy-0-0.0.1                            -14.114526
cupy-2-0.0.1                             -7.725966
pyhpc-isoneural-4-0.0.1                  -7.661059
cupy-4-0.0.1                             -5.455382
cupy-1-0.0.1                             -5.084493
squeezenet-0-0.0.1                       -2.210886

In [13]:
error_data[error_data.is_test==True][['dispatch_policy', 'percentage_relative_error']].groupby('dispatch_policy').mean().sort_values(by='percentage_relative_error')

                 percentage_relative_error
dispatch_policy
Landlord                        -56.901096

In [14]:
error_data[error_data.is_test==True][['dispatch_policy', 'absolute_error']].groupby('dispatch_policy').mean().sort_values(by='absolute_error')

                 absolute_error
dispatch_policy
Landlord               0.503659